services:
  factorio-plot:
    image: factorio-plot:local
    volumes:
      - "$HOME/.factorio/saves:/factorio-saves" # Path to factorio saves
      - ".:/app"
    stdin_open: true
    tty: true
    restart: "no"
